server:
  port: 19003

spring:
  application:
    name: torino-scheduler
  datasource:
    url: jdbc:mysql://10.225.30.176:3307/scheduler?rewriteBatchedStatements=true
    password: welcome
    username: root
  
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            clusterCheckinInterval: 5000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
          scheduler:
            instanceId: torino-scheduler

  cloud:
    consul:
      host: 10.225.25.89
      port: 32357

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    healtn:
      enabled: true